### ISSUE TITLE
not finding quasars due to spec type

### ISSUE THREAD

**Issue by alxogm** [paulmartini/baltools#6]
Hi @paulmartini  is this line not causing an issue for you when running in data, recently? 
https://github.com/paulmartini/baltools/blob/7dfa41a0187c6b9f33bca5027afd6f547b016ec6/py/baltools/desibal.py#L102

I think the 'b' in front of 'QSO' is not longer needed. For recent mocks it fails to find quasars as it is, so I'll submit a PR,  but I'm wondering if we need to retain backward compatibility, I think so, do you agree?

**Comment by paulmartini** [comment]
I have heard that byte encoding is only slowing going away, and whether it is present or not depends on the version of fitsio (or astropy) someone is using. I think would be best to handle either possibility, and I agree with you about backwards compatibility too.

**Comment by alxogm** [comment]
OK, I included a fix to this in the open PR. So I'm closing this issue. Thanks.
